[package]
name = "example-db-sea-orm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
salvo = { workspace = true, features = ["affix", "serve-static"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
serde = { version = "1.0.144", features = ["derive"] }
tera = "1.17.1"
sea-orm = { version = "0.9.2", features = [
  "debug-print",
  "runtime-tokio-native-tls",
  "sqlx-sqlite",
  # "sqlx-postgres",
  # "sqlx-mysql",
] }
async-std = { version = "^1", features = ["attributes", "tokio1"] }
sea-orm-migration = "0.9.2"
