[package]
name = "salvo-oapi"
version.workspace = true
edition = "2021"
description = "OpenApi support for salvo."
readme = "README.md"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/salvo-oapi/"
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
keywords = ["http", "async", "salvo", "openapi", "swagger-ui"]
categories = ["network-programming", "asynchronous"]
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]

[features]
default = []
debug = []

[dependencies]
salvo_core = { workspace = true, default-features = false }
salvo-oapi-macros = { workspace = true, default-features = false }
serde_urlencoded = "0.7.1"
base64 = "0.13.0"
serde = { version = "1.0.130", features = ["derive"] }
num-traits = "0.2.14"
thiserror = "1.0.30"
bytes = "1.1.0"
futures-util = "0.3.17"
derive_builder.workspace = true

# Non-feature optional dependencies
email_address = { version = "0.2.1", optional = true }
hostname-validator = { version = "1.1.0", optional = true }

# Feature optional dependencies
chrono = { version = "0.4.19", optional = true }
uuid = { version = "1", optional = true }
url = { version = "2.2.2", optional = true }
bson = { version = "2.0.0", optional = true }
rust_decimal = { version = "1.22.0", optional = true }
openapiv3 = "1.0.1"
once_cell = "1.12.0"
indexmap = "1.8.2"
tokio = "1.19.0"
tracing = "0.1.34"
rust-embed = { workspace = true, features = ["interpolate-folder-path"] }
mime_guess.workspace = true
serde_json.workspace = true

[build-dependencies]
zip.workspace = true
regex.workspace = true

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]