[package]
name = "salvo-oapi"
version.workspace = true
edition = "2021"
description = "OpenApi support for salvo."
readme = "README.md"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/salvo-oapi/"
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
keywords = ["http", "async", "salvo", "openapi", "swagger-ui"]
categories = ["network-programming", "asynchronous"]
authors = ["Juha Kukkonen <juha7kukkonen@gmail.com>", "Chrislearn Young <chrislearn@hotmail.com>"]

[features]
default = []
chrono = ["salvo-oapi-macros/chrono"]
decimal = ["salvo-oapi-macros/decimal"]
yaml = ["serde_yaml", "salvo-oapi-macros/yaml"]
uuid = ["salvo-oapi-macros/uuid"]
time = ["salvo-oapi-macros/time"]
smallvec = ["salvo-oapi-macros/smallvec"]
indexmap = ["salvo-oapi-macros/indexmap"]

[dependencies]
salvo_core = { workspace = true, default-features = false }
salvo-oapi-macros = { workspace = true, default-features = false }
serde_urlencoded.workspace = true
base64.workspace = true
serde.workspace = true
num-traits.workspace = true
thiserror.workspace = true
bytes.workspace = true
futures-util.workspace = true
inventory.workspace = true
regex.workspace = true

# Non-feature optional dependencies
email_address = { workspace = true, optional = true }
hostname-validator = { workspace = true, optional = true }

# Feature optional dependencies
url = { workspace = true, optional = true }
bson = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
once_cell.workspace = true
indexmap = { workspace = true, features = ["serde"] }
tokio.workspace = true
tracing.workspace = true
rust-embed = { workspace = true, features = ["interpolate-folder-path"] }
mime_guess.workspace = true
serde_json.workspace = true
serde_yaml = { workspace = true, optional = true }

[build-dependencies]
zip.workspace = true
regex.workspace = true

[dev-dependencies]
assert-json-diff.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
