[package]
name = "salvo-oapi"
version.workspace = true
edition = "2021"
description = "OpenApi support for salvo."
readme = "README.md"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/salvo-oapi/"
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
keywords = ["http", "async", "salvo", "openapi", "swagger-ui"]
categories = ["network-programming", "asynchronous"]
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]

[features]
default = []

[dependencies]
salvo_core = { workspace = true, default-features = false }
salvo-oapi-macros = { workspace = true, default-features = false }
serde_urlencoded.workspace = true
base64.workspace = true
serde = { workspace = true, features = ["derive"] }
num-traits.workspace = true
thiserror.workspace = true
bytes.workspace = true
futures-util.workspace = true
derive_builder.workspace = true

# Non-feature optional dependencies
email_address = { workspace = true, optional = true }
hostname-validator = { workspace = true, optional = true }

# Feature optional dependencies
chrono = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }
url = { workspace = true, optional = true }
bson = { workspace = true, optional = true }
rust_decimal = { workspace = true, optional = true }
once_cell.workspace = true
indexmap = { workspace = true, features = ["serde"] }
tokio.workspace = true
tracing.workspace = true
rust-embed = { workspace = true, features = ["interpolate-folder-path"] }
mime_guess.workspace = true
serde_json.workspace = true

[build-dependencies]
zip.workspace = true
regex.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
