[package]
name = "example-catch-panic"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1"
salvo = { workspace = true, features=["catch-panic"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
