[workspace]
members = ["crates/*", "examples/*"]
exclude = ["examples/work-with-tower", "examples/db-prisma-orm", "examples/with-listenfd", "examples/ws-chat-with-salvo-websocket"]

[workspace.package]
version = "0.38.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
rust-version = "1.64"
description = """
Salvo is a powerful and simple Rust web server framework.
"""
homepage = "https://salvo.rs"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = ["http", "async", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]

[workspace.dependencies]
aead = "0.5"
aes-gcm = "0.10"
anyhow = "1"
async-compression = "0.3"
async-session = "3"
async-trait = "0.1"
base64 = "0.21"
bson = "2"
bytes = "1"
bcrypt = "0.14"
cookie = "0.17"
chacha20poly1305 = "0.10"
cruet = "0.13"
encoding_rs = "0.8"
email_address = "0.2"
enumflags2 = "0.7"
etag = "4"
eyre = "0.6"
fastrand = "1"
form_urlencoded = "1"
futures-util = "0.3"
h3 = { version = "0.0.2", default-features = false }
h3-quinn = { version = "0.0.2", default-features = false }
headers = "0.3"
http = "0.2"
http-body-util = "0.1.0-rc.2"                                                                #{ git = "https://github.com/hyperium/http-body", rev = "0e20ca9" }
hmac = "0.12"
hex = "0.4"
hostname-validator = "1"
hyper = "=1.0.0-rc.3"
hyper-rustls = { git = "https://github.com/chrislearn/hyper-rustls.git", branch = "salvo2" }
hyper-util = { git = "https://github.com/hyperium/hyper-util.git", rev = "3c37c5b" }
indexmap = "1"
jsonwebtoken = "8"
mime = "0.3"
mime_guess = "2"
moka = "0.10"
multer = "2"
multimap = "0.9"
native-tls = "0.2"
num-traits = "0.2"
once_cell = "1"
openssl = "0.10"
opentelemetry-http = { version = "0.8", default-features = false }
opentelemetry-semantic-conventions = { version = "0.11", default-features = false }
opentelemetry-prometheus = { version = "0.12", default-features = false }
opentelemetry = { version = "0.19", default-features = false }
parking_lot = "0.12"
path-slash = "0.2"
percent-encoding = "2"
pin-project = "1"
proc-macro-crate = "1"
proc-macro-error = "1"
proc-macro2 = "1"
quinn = { version = "0.9", default-features = false }
rand = "0.8"
rcgen = "0.10"
regex = "1"
ring = "0.16"
rustls = "0.20"
rustls-pemfile = "1.0"
rust-embed = "6"
salvo_macros = { path = "./crates/macros", default-features = false }
salvo_core = { path = "./crates/core", default-features = false }
salvo_extra = { path = "./crates/extra", default-features = false }
salvo-cache = { path = "./crates/cache", default-features = false }
salvo-cors = { path = "./crates/cors", default-features = false }
salvo-csrf = { path = "./crates/csrf", default-features = false }
salvo-flash = { path = "./crates/flash", default-features = false }
salvo-oapi = { path = "./crates/oapi", default-features = false }
salvo-oapi-macros = { path = "./crates/oapi-macros", default-features = false }
salvo-otel = { path = "./crates/otel", default-features = false }
salvo-proxy = { path = "./crates/proxy", default-features = false }
salvo-rate-limiter = { path = "./crates/rate-limiter", default-features = false }
salvo-serve-static = { path = "./crates/serve-static", default-features = false }
salvo-session = { path = "./crates/session", default-features = false }
serde = "1"
serde_json = "1"
serde_urlencoded = "0.7"
sha2 = "0.10"
syn = "2"
tempfile = "3"
textnonce = "1"
thiserror = "1"
time = "0.3"
tokio = "1"
tokio-native-tls = "0.3"
tokio-rustls = "0.23"
tokio-openssl = "0.6"
tokio-stream = { version = "0.1", default-features = false }
tokio-util = "0.7"
tokio-tungstenite = { version = "0.18", default-features = false }
tracing-subscriber = { version = "0.3" }
tracing = "0.1"
tracing-test = "0.2.1"
url = "2"
quote = "1"
x509-parser = "0.15"
uuid = "0.8"
derive_builder = "0.12"
assert-json-diff = "2"
chrono = "0.4"
paste = "1"
rust_decimal = "1"
serde_with = "2"
smallvec = "1"
zip = "0.6"
