[package]
name = "example-with-socketioxide"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hyper = { workspace = true, features = ["server"] }
salvo = { workspace = true, features = ["tower-compat"] }
tokio = { workspace = true, features = ["macros"] }
tower = { version = "0.4" }
tower-http = { version = "0.4" }
serde = { workspace = true, features = ["derive"] }
socketioxide = "0.5"
tracing.workspace = true
tracing-subscriber.workspace = true
