[package]
edition = "2021"
name = "example-db-mysql-rbatis"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
once_cell = "1"
rbatis = "4.1"
rbdc = "4.1"
rbdc-mysql = "4.1"
rbs = "4.1"
salvo = { workspace = true }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.24.1", features = ["macros"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
serde_json = "1.0"
