[package]
name = "example-db-prisma-orm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "prisma-cli"
path = "src/bin/prisma.rs"

[dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", rev="e12e693", default-features = false, features = ["migrations", "sqlite"]}
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", rev="e12e693", default-features = false, features = ["migrations", "sqlite"]}

serde = { version = "1.0.144", features = ["derive"] }
salvo = { workspace = true }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.58"

tracing = "0.1.37"
tracing-subscriber = "0.3.16"