[workspace]
members = ["*"]
exclude = ["work-with-tower", "db-prisma-orm", "target"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
publish = false
rust-version = "1.65"
description = """
Salvo is a powerful and simple Rust web server framework.
"""
homepage = "https://salvo.rs"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = ["http", "async", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]

[workspace.dependencies]
anyhow = "1"
rbatis = "4.3"
rbdc = "4.3"
rbdc-mysql = "4.3"
rbs = "4.3"
async-std = "1.12"
async-trait = "0.1"
hyper = "=1.0.0-rc.3"
sea-orm = "0.11"
sea-orm-migration = "0.11"
eyre = "0.6"
tera = "1.3"
futures = "0.3"
opentelemetry = "0.19"
opentelemetry-http = "0.8.0"
opentelemetry-jaeger = "0.18.0"
opentelemetry-prometheus = "0.12.0"
utoipa = "3.3.0"
utoipa-swagger-ui = "*"
tokio-stream = "0.1.14"
async-stream = "0.3.5"
futures-util = { version = "0.3", default-features = true }
jsonwebtoken = "8"
once_cell = "1"
parking_lot = "0.12"
salvo = { path = "../crates/salvo", default-features = true }
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = "1"
tracing-subscriber = { version = "0.3" }
tracing = "0.1"
tracing-test = "0.2.1"
url = "2"
chrono = "0.4"
sqlx = "0.6"
rust-embed = "6"
time = "0.3"
