[package]
name = "example-otel-jaeger"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-otel-client"
path = "src/client.rs"

[[bin]]
name = "example-otel-server1"
path = "src/server1.rs"

[[bin]]
name = "example-otel-server2"
path = "src/server2.rs"

[dependencies]
salvo = { path = "../../crates/salvo", features = ["affix", "otel"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
opentelemetry = { version = "0.19", features = ["metrics", "rt-tokio"] }
reqwest = "0.11"
prometheus = "0.13"
opentelemetry-prometheus = "0.12.0"
opentelemetry-http = "0.8.0"
opentelemetry-jaeger = { version = "0.18.0", features = ["rt-tokio", "collector_client", "hyper_collector_client"] }
 