[package]
name = "example-session-login"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
once_cell = "1"
salvo = { workspace = true, features=["session"] }
serde = { version = "1.0.118", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"