[package]
name = "example-flash-session-store"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = { workspace = true, features=["flash", "session"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
