[package]
name = "salvo-oapi-macros"
version.workspace = true
edition = "2021"
description = "Macros for salvo"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/salvo-oapi/"
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
keywords = ["http", "async", "openapi", "swagger"]
categories = ["network-programming", "asynchronous"]
authors = ["Chrislearn Young <chislearn@hotmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
syn = { workspace = true, features = ["full", "extra-traits"] }
quote.workspace = true
proc-macro-crate.workspace = true
proc-macro-error.workspace = true
regex = { version = "1.7", optional = true }
lazy_static = { version = "1.4", optional = true }
uuid = { version = "1", optional = true }

[dev-dependencies]
salvo-oapi = { workspace = true, default-features = false }
serde_json.workspace = true
serde.workspace = true
paste.workspace = true
smallvec = { workspace = true, features = ["serde"] }
rust_decimal.workspace = true
chrono = { workspace = true, features = ["serde"] }
assert-json-diff.workspace = true
time = { workspace = true, features = ["serde-human-readable"] }
serde_with.workspace = true

[features]
debug = ["syn/extra-traits"]
chrono = []
yaml = []
decimal = []
uuid = ["dep:uuid"]
time = []
smallvec = []
repr = []
indexmap = []
