name: ci-linux

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  check:
    strategy:
        fail-fast: false
        matrix:
          version:
            - stable
            # - nightly
    name: Cargo check ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: check build
        run: cargo check --all --bins --examples --tests

      - name: check release build
        run: cargo check --all --bins --examples --tests --release

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: check --feature-powerset
        run: cargo hack check --feature-powerset --depth 1 avoid-dev-deps

  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: Test ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: Cargo test
        timeout-minutes: 40
        run: cargo test --all --all-features --no-fail-fast -- --nocapture

  cover:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: Coverage ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: Generate coverage file
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/main' || github.event_name == 'push')
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --all-features -p salvo_macros salvo_core salvo_extra salvo-session salvo-flash salvo-cors salvo-csrf salvo-cache salvo-proxy salvo-rate-limiter salvo-serve-static --out Xml

      - name: Upload to codecov
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/main' || github.event_name == 'push')
        uses: codecov/codecov-action@v3
        with:
          file: cobertura.xml