name: ci-macos

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: Check ${{ matrix.version }} - x86_64-apple-darwin
    runs-on: macOS-12

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: check build
        run: cargo check --all --bins --examples --tests

      - name: check release build
        run: cargo check --all --bins --examples --tests --release

  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: Test ${{ matrix.version }} - x86_64-apple-darwin
    runs-on: macOS-12
    needs: [check]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy
          
      - name: Cargo test
        timeout-minutes: 40
        run: cargo test --all --all-features --no-fail-fast -- --nocapture