name: ci-windows

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly
        target:
          - x86_64-pc-windows-msvc
          # - x86_64-pc-windows-gnu
          # - i686-pc-windows-msvc

    name: Check ${{ matrix.version }} - ${{ matrix.target }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: check build
        run: cargo check --all --bins --examples --tests

      - name: check release build
        run: cargo check --all --bins --examples --tests --release


  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly
        target:
          - x86_64-pc-windows-msvc
          # - x86_64-pc-windows-gnu
          # - i686-pc-windows-msvc

    name: Test ${{ matrix.version }} - ${{ matrix.target }}
    runs-on: windows-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy
          
      - name: Cargo test
        timeout-minutes: 40
        run: cargo test --all --all-features --no-fail-fast -- --nocapture